// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQm33is3768qSs553rzXNBYdP9Kal_ZtI',
    appId: '1:469823726976:web:5658c0deed8a7b30dccd65',
    messagingSenderId: '469823726976',
    projectId: 'ireader-af97b',
    authDomain: 'ireader-af97b.firebaseapp.com',
    storageBucket: 'ireader-af97b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvHSeGCT0MTdhe4z7DW7p5juwPC3bGdIs',
    appId: '1:469823726976:android:1ad8d845d567451cdccd65',
    messagingSenderId: '469823726976',
    projectId: 'ireader-af97b',
    storageBucket: 'ireader-af97b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJCQvSEYOtOX-4WCjgbyTdn4YT6B65z5g',
    appId: '1:469823726976:ios:76868d1e33f3698fdccd65',
    messagingSenderId: '469823726976',
    projectId: 'ireader-af97b',
    storageBucket: 'ireader-af97b.firebasestorage.app',
    iosBundleId: 'com.example.ireaderWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJCQvSEYOtOX-4WCjgbyTdn4YT6B65z5g',
    appId: '1:469823726976:ios:76868d1e33f3698fdccd65',
    messagingSenderId: '469823726976',
    projectId: 'ireader-af97b',
    storageBucket: 'ireader-af97b.firebasestorage.app',
    iosBundleId: 'com.example.ireaderWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQm33is3768qSs553rzXNBYdP9Kal_ZtI',
    appId: '1:469823726976:web:5c35415cd285f1e4dccd65',
    messagingSenderId: '469823726976',
    projectId: 'ireader-af97b',
    authDomain: 'ireader-af97b.firebaseapp.com',
    storageBucket: 'ireader-af97b.firebasestorage.app',
  );
}
